"""Update tables

Revision ID: 201135469e38
Revises: 8e2d1e407d98
Create Date: 2024-07-10 18:39:50.773577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201135469e38'
down_revision: Union[str, None] = '8e2d1e407d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('reviewer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'review', 'user', ['reviewer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'reviewer_id')
    op.drop_constraint(None, 'bid', type_='foreignkey')
    op.drop_column('bid', 'bidder_id')
    # ### end Alembic commands ###
