"""Update user table

Revision ID: 8e2d1e407d98
Revises: 40137ab018a5
Create Date: 2024-07-09 20:40:36.777858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e2d1e407d98'
down_revision: Union[str, None] = '40137ab018a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'token',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=320),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'token',
               existing_type=sa.String(length=320),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
